include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
linter:
  rules:
    avoid_dynamic_calls: true
    public_member_api_docs: false